---
name: Checks

on: [ push ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Creating env file
        run: cp .env.example .env

      - name: Creating app Image
        run: docker compose run --rm app sh -c "echo 'ok'"

      - name: Flake8
        run: docker compose run --rm app sh -c "flake8"

      - name: Black
        run: docker compose run --rm app sh -c "black ."

      - name: Start Mysql Service
        run: docker compose up -d db

      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Destroy Mysql Service
        run: docker compose down
