---
name: Checks

on: [ push ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Creating env file
        run: cp .env.example .env

      - name: Creating app Image
        run: docker compose run --rm app sh -c "echo 'ok'"

      - name: Flake8
        run: docker compose run --rm app sh -c "flake8"

      - name: Black
        run: docker compose run --rm app sh -c "black ."

      - name: Start PostgreSQL Service
        run: docker compose up -d db

      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Destroy PostgreSQL Service
        run: docker compose down

  build:
    needs: test-lint
    name: Build and Push to PROD
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            lucasaraujo1301/posts_api:api-latest
          cache-from: type=registry,ref=lucasaraujo1301/posts_api:buildcache
          cache-to: type=registry,ref=lucasaraujo1301/posts_api:buildcache,mode=max